### ISSUE TITLE
Translate into English then search

### ISSUE THREAD

**Issue by ChrisTorng** [Hatisoft/SearchErrorOn#10]
I'm using Traditional Chinese Windows, with Traditional Chinese Visual Studio 2013. Usually searching in Traditional Chinese gets a few results. I always using http://www.microsoft.com/Language/en-US/Search.aspx to translate Traditional Chinese text into English to search, gets a lot of results. If you can support translation, than it will be a useful extension to us that is not using English in Windows/.NET.

**Comment by alvarolorentedev** [comment]
sounds like a good improvement to do, I will look at some translation provider, and add an option to translate or not to English (or other if possible). 

could i ask for a favour? I will try to do an alpha release of this functionality as soon as possible,  as i don't have a machine with Traditional Chinese, when its done can you help me test it?

**Comment by ChrisTorng** [comment]
I'm glad to help.

But hope you can stick on the service I provided. That's exactly mapping between other languages and English provided by the author of Windows/.NET Framework. You can use double quotes "search term" to do exactly search (after deleted variables), that can narrow results into only the right targets.

Like search "工作指定必要參數" (without double quotes) from "Chinese Trad. (Taiwan)" to English, you get Translation "MSB4044: 沒有為 "{0}" 工作指定必要參數 "{1}" 的值。" with English 'MSB4044: The "{0}" task was not given a value for the required parameter "{1}".'. Then you can do exactly search "task was not given a value for the required parameter" with double quotes. Or 'MSB4044: The "task was not given a value for the required parameter"' (without single quotes), that gets the best results.

**Comment by alvarolorentedev** [comment]
well i cannot stick to that service because it doesn't provide an API to translate, neither their search engine provides a PUT method, so I could added as a new search engine.

Google and Microsoft have their translation engines I could use (but of course it wont be the same), plus they are paid for. 

I would appreciate if you have any extra idea or resource that could help.

**Comment by ChrisTorng** [comment]
How about this one http://www.microsoft.com/Language/en-US/Microsoft-Terminology-API.aspx ? If you use other translation service, then I will think it is almost useless. I can give it a try and give you feedback, but I still think the "double quotes exactly" search can give me only pages that I need. I don't want to look through other looks-alike but not exactly pages.

**Comment by alvarolorentedev** [comment]
ok thanks for the link...will look at this API reference :)

**Comment by alvarolorentedev** [comment]
🙏  Sorry For the late reply, I did not get the notification so have not seen this issue 🙏 

In reality i was never able to find anything that helped

**Comment by ChrisTorng** [comment]
I found the new [Microsoft Terminology Service API](https://www.microsoft.com/en-us/language/Microsoft-Terminology-API) that may help. Although it has no zh-tw support, but still can be used for other supported languages.
